# Generated by Django 5.0 on 2023-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_author_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
