# Generated by Django 5.0 on 2023-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='downloads_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
