# Generated by Django 5.0 on 2023-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_downloads_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
    ]
