# Generated by Django 5.0 on 2023-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='book.book'),
        ),
    ]
